name: Check markdown links

on:
  repository_dispatch:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  schedule:
    # every sunday at 12:00
    - cron: "00 12 * * 0"  # https://crontab.guru/#00_12_*_*_0

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: --exclude 'https://www\.hpe\.com/us/en/greenlake\.html' --exclude 'https://www\.hpe\.com/us/en/private-cloud-ai\.html' --exclude 'https://www\.intel\.com/content/www/us/en/developer/tools/cnvrg/overview\.html' README.md
         
      - name: Create Issue From File
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@main
        with:
          title: "[Bot] Broken Links Report"
          content-filepath: ./lychee/out.md
          labels: report
